#!/bin/sh
export ENV="${HOME}/.shrc"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_STATE_HOME="${HOME}/.local/state"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

mkdir -p "${XDG_STATE_HOME}"

if [ -n "${SSH_CLIENT}" -a "${TERM}" = "foot" ]; then
  export TERM="xterm-256color"
fi

has() {
  command -v "$1" 1>/dev/null
}

if has ssh-agent && [ -z "${SSH_AGENT_PID}" ]; then
  eval $(ssh-agent)
fi

try_exec_dbus() {
  local _cmd=$1; shift
  local _log="${XDG_STATE_HOME}/${_cmd}.log"

  if has dbus-run-session; then
    exec dbus-run-session -- "$_cmd" "$@" 1>"$_log" 2>&1
  else
    exec "$_cmd" "$@" 1>"$_log" 2>&1
  fi
}

exec_sway() {
  export MOZ_ENABLE_WAYLAND="1"
  export QT_QPA_PLATFORM="wayland-egl"
  export XDG_CURRENT_DESKTOP="sway"
  try_exec_dbus sway
}

case "$TTY" in
  "/dev/tty1") has sway && exec_sway;;
esac
