#!/bin/sh
export ENV="${HOME}/.shrc"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DOWNLOAD_DIR="${HOME}/Downloads"
export XDG_STATE_HOME="${HOME}/.local/state"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

mkdir -p "${XDG_STATE_HOME}"

if [ -n "${SSH_CLIENT}" -a "${TERM}" = "foot" ]; then
  export TERM="xterm-256color"
fi

has() {
  command -v "$1" 1>/dev/null
}

if has ssh-agent && [ -z "${SSH_AGENT_PID}" ]; then
  eval "$(ssh-agent -s)" > /dev/null
fi
