font            = "Noto Sans 11"
monospaceFont   = "Noto Sans Mono 11"
gtkTheme        = "Catppuccin-Mocha-Standard-Sapphire-Dark"
unixCursorTheme = "capitaine-cursors-light"
unixCursorSize  = "48"

[gitaliases]
A   = "add -A"
a   = "add"
cb  = "checkout -b"
co  = "checkout"
cm  = "commit -m"
d   = "diff"
dc  = "diff --cached"
dcs = "diff --cached --stat"
df  = "diff"
ds  = "diff --stat"
f   = "fetch --prune"
ph  = "push"
s   = "status"
