font            = "Noto Sans 11"
monospaceFont   = "Noto Sans Mono 11"
gtkTheme        = "Catppuccin-Mocha-Standard-Sapphire-Dark"
unixCursorTheme = "capitaine-cursors-light"
unixCursorSize  = "48"

[aliases]
cza = "chezmoi apply"
czu = "chezmoi update"

[gitaliases]
a   = "add"
all = "add --all"
cb  = "checkout -b"
co  = "checkout"
ca  = "commit --amend --no-edit"
cm  = "commit -m"
d   = "diff"
dc  = "diff --cached"
dcs = "diff --cached --stat"
df  = "diff"
ds  = "diff --stat"
f   = "fetch --prune"
l   = "log --oneline"
ph  = "push"
phf = "push --force"
s   = "status --short"
