font            = "Noto Sans 11"
monospaceFont   = "Noto Sans Mono 11"
gtkTheme        = "Catppuccin-Mocha-Standard-Sapphire-Dark"
unixCursorTheme = "capitaine-cursors-light"
unixCursorSize  = "48"

[aliases]
cza = "chezmoi apply"
czu = "chezmoi update"

[gitaliases]
a    = "add"
all  = "add --all"
ca   = "commit --amend --no-edit"
cb   = "checkout -b"
cm   = "commit -m"
co   = "checkout"
d    = "diff"
dc   = "diff --cached"
dcs  = "diff --cached --stat"
df   = "diff"
ds   = "diff --stat"
f    = "fetch --prune"
hard = "reset --hard"
l    = "log --oneline"
p    = "push"
pf   = "push --force"
pl   = "pull"
r    = "rebase"
ra   = "rebase --abort"
rc   = "rebase --continue"
s    = "status --short"
soft = "reset --soft"
