#!/usr/bin/env zsh

if command -v starship > /dev/null; then
  eval `starship init zsh`
  eval `starship completions zsh`
fi

for file in ${HOME}/.zsh/*.zsh; do
  source "${file}"
done

source "${HOME}/.shrc"
