#!/bin/sh
export ENV="${HOME}/.shrc"
export XDG_CONFIG_HOME="${HOME}/.config"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

if test `uname` = "FreeBSD" && test "${TERM}" = "foot"; then
  export TERM="xterm-256color"
fi

if command -v ssh-agent > /dev/null && test -z "${SSH_AGENT_PID}"; then
  eval $(ssh-agent)
fi

if test "$TTY" = "/dev/tty1"; then
  if command -v sway > /dev/null; then
    if command -v dbus-run-session > /dev/null; then
      exec dbus-run-session -- sway
    else
      exec sway
    fi
  fi
fi
