#!/bin/sh

if uname -r | grep -q microsoft; then
  julie_fix_wsl_interop() {
    if ! test -e ${WSL_INTEROP}; then
      _pid="${PPID}"

      while test -n "${_pid}"; do 
        if test -e "/run/WSL/${_pid}_interop"; then
          export WSL_INTEROP="/run/WSL/${_pid}_interop"
          break
        fi
        _pid=$(awk '$1 == "PPid:" { print $2 }' "/proc/${_pid}/status")
      done
    fi
  }
  julie_fix_wsl_interop
fi

julie_has_command() {
  command -v $1 > /dev/null
}

if julie_has_command doas && ! julie_has_command sudo; then
  alias sudo=doas
elif julie_has_command sudo && ! julie_has_command doas; then
  alias doas=sudo
fi

if julie_has_command nvim; then
  alias vim=nvim
  export MANPAGER='nvim +Man!'
  export EDITOR=nvim
elif julie_has_command vim; then
  alias nvim=vim
elif julie_has_command vi; then
  alias nvim=vi
  alias vim=vi
fi

if uname -r | grep -q microsoft; then
  julie_init_wsl
fi

unset -f julie_has_command

if test -e "${HOME}/.cargo/env"; then
  source "${HOME}/.cargo/env"
fi
