#!/bin/sh

if uname -r | grep -q microsoft; then
  julie_fix_wsl_interop() {
    if ! test -e ${WSL_INTEROP}; then
      _pid="${PPID}"

      while test -n "${_pid}"; do 
        if test -e "/run/WSL/${_pid}_interop"; then
          export WSL_INTEROP="/run/WSL/${_pid}_interop"
          break
        fi
        _pid=$(awk '$1 == "PPid:" { print $2 }' "/proc/${_pid}/status")
      done
    fi
  }
  julie_fix_wsl_interop
fi

has() {
  command -v $1 > /dev/null
}

set -o vi

export PATH="${HOME}/.local/bin${PATH:+:${PATH}}"
export HISTFILE="${HOME}/.history"
export HISTSIZE=10000
export SAVESIZE=10000

if has doas && ! has sudo; then
  alias sudo=doas
elif has sudo && ! has doas; then
  alias doas=sudo
fi

if has nvim; then
  alias vim=nvim
  export MANPAGER='nvim +Man!'
  export EDITOR=nvim
elif has vim; then
  alias nvim=vim
  export EDITOR=vim
elif has vi; then
  alias nvim=vi
  alias vim=vi
  export EDITOR=vi
fi

if has exa; then
  alias ls='exa'
  alias ll='exa -l --git'
  alias la='exa -la --git'
  alias tree='exa -Tla --git'
else
  alias ll='ls -l'
  alias la='ls -la'
fi

. "${HOME}/.aliases"

if test -e "${HOME}/.cargo/env"; then
  . "${HOME}/.cargo/env"
fi

if has apk; then
  apk list --upgradeable
fi
