#!/bin/sh

if uname -r | grep -q microsoft; then
  julie_fix_wsl_interop() {
    if ! test -e ${WSL_INTEROP}; then
      _pid="${PPID}"

      while test -n "${_pid}"; do 
        if test -e "/run/WSL/${_pid}_interop"; then
          export WSL_INTEROP="/run/WSL/${_pid}_interop"
          break
        fi
        _pid=$(awk '$1 == "PPid:" { print $2 }' "/proc/${_pid}/status")
      done
    fi
  }
  julie_fix_wsl_interop
fi

julie_has_command() {
  command -v $1 > /dev/null
}

set -o vi

export PATH="${HOME}/.local/bin${PATH:+:${PATH}}"
export HISTFILE="${HOME}/.history"
export HISTSIZE=10000
export SAVESIZE=10000

if julie_has_command doas && ! julie_has_command sudo; then
  alias sudo=doas
elif julie_has_command sudo && ! julie_has_command doas; then
  alias doas=sudo
fi

if julie_has_command nvim; then
  alias vim=nvim
  export MANPAGER='nvim +Man!'
  export EDITOR=nvim
elif julie_has_command vim; then
  alias nvim=vim
  export EDITOR=vim
elif julie_has_command vi; then
  alias nvim=vi
  alias vim=vi
  export EDITOR=vi
fi

if julie_has_command exa; then
  alias ls='exa'
  alias ll='exa -l --git'
  alias la='exa -la --git'
  alias tree='exa -Tla --git'
else
  alias ll='ls -l'
  alias la='ls -la'
fi

. "${HOME}/.aliases"

if test -e "${HOME}/.cargo/env"; then
  . "${HOME}/.cargo/env"
fi

unset -f julie_has_command
