#!/bin/sh

if command -v ssh-agent > /dev/null && test -z "${SSH_AGENT_PID}"; then
  eval $(ssh-agent)
fi

if test -z "${TMUX}" && command -v tmux > /dev/null; then
  if tmux attach; then
    exit
  else
    exec "${HOME}/dotfiles/tmux/main-session"
  fi
fi
