#!/bin/sh
if ! test -e ${WSL_INTEROP}; then
  _pid="${PPID}"

  while test -n "${_pid}"; do 
    if test -e "/run/WSL/${_pid}_interop"; then
      export WSL_INTEROP="/run/WSL/${_pid}_interop"
      break
    fi
    _pid=$(awk '$1 == "PPid:" { print $2 }' "/proc/${_pid}/status")
  done
fi
