#!/usr/bin/env zsh

source "${HOME}/.shrc"

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search

if has starship; then
  eval "$(starship init zsh)"
fi

if has brew; then
  source_if_has "${HOMEBREW_PREFIX}/opt/nvm/etc/bash_completion.d/nvm" 
fi

export HISTFILE="${HOME}/.zsh_history"

setopt append_history
setopt auto_cd
setopt auto_pushd
setopt globdots
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt interactivecomments
setopt no_beep

bindkey -v
bindkey -M vicmd k up-line-or-beginning-search
bindkey -M vicmd j down-line-or-beginning-search
bindkey -M viins "${terminfo[kcuu1]}" up-line-or-beginning-search 
bindkey -M viins "${terminfo[kcud1]}" down-line-or-beginning-search 
