#!/bin/sh
set -e
cd $(dirname $0)
. ./shared.sh

_target_user=`_get_target_user`

./alpine-base
./alpine-edge

apk add --virtual .julie-desktop \
  capitaine-cursors \
  chromium \
  eudev \
  firefox \
  foot \
  imv \
  less \
  libinput \
  mesa-dri-gallium \
  pm-utils \
  seatd \
  sway \
  swaybg \
  swayidle \
  swaylock \
  waybar \
  wl-clipboard \
  wlr-randr \
  xwayland 

./alpine-fonts 

_openrc_enable seatd

_append_line /etc/doas.conf "permit nopass :wheel cmd pm-suspend" 

if test -n "${_target_user}"; then
  adduser "${_target_user}" audio
  adduser "${_target_user}" input
  adduser "${_target_user}" seat
  adduser "${_target_user}" video
fi

echo "Setting XDG_RUNTIME_DIR"
cat << EOF > /etc/profile.d/julie-xdg-runtime-dir.sh
if test -z "\${XDG_RUNTIME_DIR}"; then
  export XDG_RUNTIME_DIR="/tmp/\$(id -u)-runtime-dir"
  if ! test -d "\${XDG_RUNTIME_DIR}"; then
    mkdir -m 0700 "\${XDG_RUNTIME_DIR}"
  fi
fi
EOF
