#!/bin/sh
set -e
cd $(dirname $0)
. ./shared.sh

_check_root

_julie_shell=/bin/zsh
_julie_tz=Europe/Prague
_julie_user=`_get_target_user || echo ""`

echo "Upgrading packages"
apk update
apk upgrade 

echo "Installing .julie-alpine-base"
apk add --virtual .julie-alpine-base \
  chezmoi \
  curl \
  doas \
  docs \
  exa \
  fzf \
  git \
  htop \
  jq \
  man-pages \
  mandoc \
  neovim \
  openntpd \
  openssh \
  ripgrep \
  shadow \
  starship \
  tzdata \
  zsh \
  ;

echo "Installing .julie-alpine-samba"
apk add --virtual .julie-alpine-samba \
  samba \
  wsdd \
  ;

echo "Disabling nmbd"
echo 'daemon_list="smbd"' > /etc/conf.d/samba
echo 'smbd_options="-D"' >> /etc/conf.d/samba

_openrc_enable openntpd
_openrc_enable samba
_openrc_enable sshd
_openrc_enable syslog
_openrc_enable wsdd

if ! pdbedit --list --user "${_julie_user}" 2> /dev/null; then
  echo "Creating Samba user ${_julie_user}"
  pdbedit --create --user "${_julie_user}"
fi

_append_line /etc/conf.d/consolefont 'consolefont="ter-124b.psf.gz"'
_openrc_enable consolefont boot

_append_line /etc/doas.conf "permit persist :wheel" 

echo "Setting TZ to ${_julie_tz}"
echo "export TZ='${_julie_tz}'" > /etc/profile.d/julie-timezone.sh

echo "Emptying /etc/motd"
: > /etc/motd

if test -n "${_julie_user}"; then
  echo "Changing ${_julie_user}'s shell to ${_julie_shell}"
  usermod --shell "${_julie_shell}" "${_julie_user}" 
fi

