#!/bin/sh
set -e
cd "$(dirname $0)"
. ./shared.sh

_check_root
_user=`_get_target_user`
_uid=`id -u "${_user}"`

if test "${_uid}" = "0"; then
  echo "Target user is root, skipping user config." >&2
  unset _uid
  unset _user
elif test "${_uid}" -lt 1000 || test "${_uid}" -gt 9999; then
  echo "Target user has a weird uid, skipping user config." >&2
  unset _uid
  unset _user
fi

# fuse needed for ZFS, hopefully won't be needed after OpenZFS 2.2
echo "Adding podman, fuse, and fuse-overlayfs"
apk add -t .julie-podman \
  podman \
  fuse \
  fuse-overlayfs

_openrc_enable cgroups
_insert_mod fuse
_insert_mod tun

_append_line /etc/rc.conf \
  "rc_cgroup_mode=\"hybrid\" # @juliekoubova/dotfiles alpine-podman"

if test -z "${_uid}"; then
  exit
fi

_first=$(( ${_uid} * 100000 ))
_last=$(( ( (${_uid}+1) * 100000 ) - 1 ))

echo "Adding subuids and subgids for ${_user}"
usermod --add-subuids "${_first}-${_last}" \
        --add-subgids "${_first}-${_last}" \
        "${_user}"

