#!/bin/sh
set -e
cd "$(dirname $0)"


if ! test -d /boot/efi/efi; then
  mount -t msdos /dev/disk/by-label/EFI /boot/efi
fi

mkdir -p /boot/efi/EFI/zbm

mkdir -p /etc/zfsbootmenu
mkdir -p /etc/zfsbootmenu/mkinitcpio.conf.d
mkdir -p /etc/zfsbootmenu/rc.d

cat > /etc/zfsbootmenu/config.yaml <<EOF
Global:
  InitCPIO: true
Components:
  Enabled: false
EFI:
  Enabled: true
  Versions: false
Kernel:
  Prefix: zfsbootmenu
  CommandLine: zfsbootmenu ro loglevel=6 video=2560x1440
EOF

cat > /etc/zfsbootmenu/mkinitcpio.conf.d/consolefont.conf <<EOF
BINARIES+=(setfont)
HOOKS+=(consolefont)
EOF

cat > /etc/zfsbootmenu/rc.d/consolefont <<EOF
#!/bin/sh
sed -e '/FONT=/a FONT="ter-124b"' -i /etc/rc.conf
EOF

chmod 755 /etc/zfsbootmenu/rc.d/consolefont

cd /etc/zfsbootmenu
curl -L -o /etc/zfsbootmenu/zbm-builder.sh \
  https://raw.githubusercontent.com/zbm-dev/zfsbootmenu/master/zbm-builder.sh
chmod 755 /etc/zfsbootmenu/zbm-builder.sh

/etc/zfsbootmenu/zbm-builder.sh

cp /boot/efi/efi/boot/bootx64.efi /boot/efi/efi/boot/bootx64-.efi
cp /etc/zfsbootmenu/build/zfsbootmenu.EFI /boot/efi/efi/boot/bootx64.efi
