#!/bin/sh
set -e

: ${arch:=armv7}
: ${rel:=v3.18}
: ${tgz:=alpine-rpi-3.18.2-${arch}.tar.gz}
: ${mirror:=https://dl-cdn.alpinelinux.org}
: ${workdir:=/tmp/build-rpi}

function _exit() {
  echo >&2 $@
  exit 1
}

function _warn_var() {
  local _value=$(env | awk -F= "\$1 == ${1} { print \$2 }")
  test -n "${_value}" || echo >&2 "warning: ${1} not set"
}

function _fetch() {
  if test -f "${1}"; then
    echo "Already got ${1}"
  else
    echo "Downloading ${1}"
    curl --progress-bar --output "${1}" "${2}"
  fi
}

test `id -u` = "0" || _exit "must be root"
test -b "${1}" || _exit "usage: ${0} /dev/sdX"

_warn_var rpi_wpa_ssid
_warn_var rpi_wpa_psk

disk="${1}"
part="${disk}1"
mnt="${workdir}/mnt"
ovl="${workdir}/ovl"

sha="${tgz}.sha256"

base_url="${mirror}/alpine/${rel}/releases/${arch}"
tgz_url="${base_url}/${tgz}"
sha_url="${base_url}/${sha}"

repo_url="${mirror}/alpine/${rel}/main"
repo_file="${workdir}/repositories"

mkdir -p "${workdir}"
mkdir -p "${mnt}"
mkdir -p "${ovl}"

test -d "${ovl}" && rm -rf "${ovl}"

cd -- "${workdir}"

_fetch "${sha}" "${sha_url}"
_fetch "${tgz}" "${tgz_url}"

echo "Veryfying checksums"
sha256sum -cs "${sha}" || _exit "sha256sum doesn't match"

if mount | grep -q "${disk}"; then
  echo "Unmounting ${disk}"
  umount ${disk}?
fi

sfdisk "${disk}" <<EOF
label: dos
start=2048, type=c, name=alpine, bootable
EOF

echo "Creating FAT32"
mkdosfs -F32 "${part}"

echo "Installing syslinux bootloader"
dd bs=440 count=1 conv=notrunc if=/usr/share/syslinux/mbr.bin "of=${disk}"

echo "Installing syslinux files"
syslinux "${part}"

echo "Mounting the partition"
mount -t vfat "${part}" "${mnt}"

echo "Extracting ${tgz}"
tar x -z -o -v --no-same-permissions \
  -f "${workdir}/${tgz}" \
  -C "${mnt}" 

echo "Configuring auto-login"
mkdir -p "${ovl}/etc"
cat > "${ovl}/etc/inittab" <<EOF
::sysinit:/sbin/openrc sysinit
::sysinit:/sbin/openrc boot
::wait:/sbin/openrc default

tty1::respawn:/bin/login -f root
tty2::respawn:/sbin/getty tty2
tty3::respawn:/sbin/getty tty3
tty4::respawn:/sbin/getty tty4
tty5::respawn:/sbin/getty tty5
tty6::respawn:/sbin/getty tty6

# Put a getty on the serial port
#ttyS0::respawn:/sbin/getty -L ttyS0 115200 vt100

# Stuff to do for the 3-finger salute
::ctrlaltdel:/sbin/reboot

# Stuff to do before rebooting
::shutdown:/sbin/openrc shutdown
EOF

echo "Configuring network interfaces"
mkdir -p "${ovl}/etc/network"
cat > "${ovl}/etc/network/interfaces" <<EOF
auto lo
iface lo inet loopback

auto wlan0
iface wlan0 inet dhcp
iface wlan0 inet6 auto
EOF

mkdir -p "${ovl}/etc/runlevels/sysinit"
ln -s /etc/init.d/networking     "${ovl}/etc/runlevels/sysinit"
ln -s /etc/init.d/wpa_supplicant "${ovl}/etc/runlevels/sysinit"

mkdir -p "${ovl}/etc/runlevels/default"
ln -s /etc/init.d/sshd       "${ovl}/etc/runlevels/default"
ln -s /etc/init.d/openntpd   "${ovl}/etc/runlevels/default"

mkdir -p "${ovl}/etc/ssh"
cat > "${ovl}/etc/ssh/sshd_config" <<EOF
AuthenticationMethods none
PermitEmptyPasswords yes
PermitRootLogin yes
EOF

mkdir -p "${ovl}/etc/profile.d"
cat > "${ovl}/etc/profile.d/show-ip.sh" <<EOF
ip addr
EOF

mkdir -p "${ovl}/etc/wpa_supplicant"
cat > "${ovl}/etc/wpa_supplicant/wpa_supplicant.conf" <<EOF
country=CZ
network={
  key_mgmt=WPA-PSK
  ssid="${rpi_wpa_ssid}"
  psk="${rpi_wpa_psk}"
}
EOF

echo "Creating overlay"
tar c -z -f "${mnt}/build-rpi.apkovl.tar.gz" -C "${ovl}" .

echo "Unmounting"
umount "${part}"
