#!/bin/sh

install_link() {
  local _dotfile _link
  _dotfile="${HOME}/dotfiles/$1"
  _link="
if test -e "${HOME}/.profile"; then
  echo "Already exists, skipping: ${HOME}/.profile" >&2
else
  echo ". ~/dotfiles/unix/profile" > "${HOME}/.profile" || exit 1
fi

if test -e "${HOME}/.zprofile"; then
  echo "Already exists, skipping: ${HOME}/.zprofile" >&2
else
  echo ". ~/dotfiles/unix/zprofile" > "${HOME}/.zprofile" || exit 1
fi

mkdir -p "${HOME}/.config" || exit 1

if test -e "${HOME}/.config/starship.toml"; then
fi
