#!/bin/sh

_config_dir="${HOME}/.config/nvim"
_dotfiles_dir="${HOME}/dotfiles/vim"

if test -e "${_config_dir}"; then
  echo "Already exists: ${_config_dir}" >&2
  exit 1
fi

ln -s "${_dotfiles_dir}" "${_config_dir}" || exit 1
