#!/bin/sh

if uname -r | grep -q microsoft; then
  git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"
fi

git config --global user.name "Julie Koubova"
git config --global user.email "julie@koubova.net"
