#!/bin/sh
_dotfiles="${HOME}/dotfiles"

function link_dotfile() {
  local _dotfile _link
  _dotfile="${_dotfiles}/$1"
  _link="${HOME}/$2"

  if test -e "${_link}"; then
    echo "Already exists, skipping: ${_link}" >&2
  else
    mkdir -p $(dirname "${_link}") || exit 1
    ln -v -s "${_dotfile}" "${_link}" || exit 1
  fi
}


link_dotfile starship.toml  .config/starship.toml 
link_dotfile tmux/tmux.conf .tmux.conf
link_dotfile unix/foot.ini  .config/foot/foot.ini
link_dotfile unix/profile   .profile
link_dotfile unix/zprofile  .zprofile
link_dotfile unix/zshrc     .zshrc
