#!/bin/sh

if uname -r | grep -q microsoft; then
  "${HOME}/dotfiles/wsl/fix_wsl_interop"
  _wsl_path="${HOME}/dotfiles/wsl"
  export PATH="${_wsl_path}:$(echo "${PATH}" | sed -r "s,(^|:)${_wsl_path}($|:),,g")"
fi

[ -z "$TMUX"  ] && { tmux attach || exec tmux new-session && exit;}
