#!/usr/bin/env zsh

autoload -U compinit; compinit

if command -v starship > /dev/null; then
  eval `starship init zsh`
fi

source "${HOME}/.shrc"
export HISTFILE="${HOME}/.zsh_history"

setopt append_history
setopt auto_cd
setopt auto_pushd
setopt globdots
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt interactivecomments
setopt no_beep

bindkey -v
bindkey -M vicmd k vi-up-line-or-history
bindkey -M vicmd j vi-down-line-or-history
