#!/usr/bin/env zsh

autoload -U compinit; compinit
_comp_options+=(globdots) 

if command -v starship > /dev/null; then
  eval `starship init zsh`
  eval `starship completions zsh`
fi

source "${HOME}/.shrc"

setopt HIST_SAVE_NO_DUPS
