#!/bin/sh
set -e

_julie_shell=/bin/zsh
_julie_tz=Europe/Prague
_julie_groups="wheel"

if test `id -u` != "0"; then
  echo "Must be root" >&2
  exit 1
fi

_julie_user="${DOAS_USER:-${SUDO_USER}}"
if test -z "${_julie_user}"; then
  echo "DOAS_USER nor SUDO_USER not set, skipping user config." >&2
  echo "Make sure to run this script again using doas/sudo under your account." >&2
  echo >&2
fi

function _enable_service() {
  echo "Configuring $1"
  rc-update add "$1"
  rc-service "$1" start
}

echo "Upgrading packages"
apk update
apk upgrade

echo "Installing .julie-alpine-base"
apk add --virtual .julie-alpine-base \
  apk-tools-doc \
  chezmoi \
  curl curl-doc \
  doas doas-doc \
  exa exa-doc \
  fzf fzf-doc \
  git git-doc \
  htop htop-doc \
  man-pages \
  mandoc \
  neovim neovim-doc \
  openntpd openntpd-doc \
  openrc-doc \
  openssh openssh-doc \
  shadow shadow-doc \
  starship \
  tzdata tzdata-doc \
  zsh zsh-doc

_enable_service openntpd
_enable_service sshd

echo "Configuring doas"
echo "permit persist :wheel" > /etc/doas.d/julie-wheel.conf

echo "Setting TZ to ${_julie_tz}"
echo "export TZ='${_julie_tz}'" > /etc/profile.d/julie-timezone.sh

if test -n "${_julie_user}"; then
  echo "Changing ${_julie_user}'s shell to ${_julie_shell}"
  usermod --shell "${_julie_shell}" "${_julie_user}" 
fi

