#!/bin/sh
set -e

if test `id -u` != "0"; then
  echo "Must be root" >&2
  exit 1
fi

_user="${DOAS_USER:-${SUDO_USER}}"
if test -z "${_user}"; then
  echo "DOAS_USER nor SUDO_USER not set, skipping user config." >&2
  echo "Make sure to run this script again using doas/sudo under your account." >&2
  echo >&2
fi

_uid=`id -u "${_user}"`
if test "${_uid}" = "0"; then
  echo "Target user is root, skipping user config." >&2
  unset _uid
  unset _user
fi

if test "${_uid}" -lt 1000 || test "${_uid}" -gt 9999; then
  echo "Target user has a weird uid, skipping user config." >&2
  unset _uid
  unset _user
fi

function _append_line() {
  local _file _line
  _file=$1
  _line=$2
  if grep -qxF "${_line}" "${_file}"; then
    echo "${_file} already contains ${_line}"
  else
    echo "Adding ${_line} to ${_file}"
    echo "${_line}" >> "${_file}"
  fi
}

function _insert_mod() {
  echo "Enabling $1"
  modprobe "$1"
  _append_line /etc/modules "$1"
}

echo "Adding podman, fuse, and fuse-overlayfs"
apk add -t .podman \
  podman podman-doc \
  fuse fuse-doc \
  fuse-overlayfs fuse-overlayfs-doc

echo "Enabling cgroups"
rc-update add cgroups 
rc-service cgroups start 

_insert_mod fuse
_insert_mod tun

_append_line /etc/rc.conf \
  "rc_cgroup_mode=\"hybrid\" # @juliekoubova/dotfiles/alpine/podman"

if test -z "${_uid}"; then
  exit
fi

_first=$(( ${_uid} * 100000 ))
_last=$(( ( (${_uid}+1) * 100000 ) - 1 ))

echo "Adding subuids and subgids for ${_user}"
usermod --add-subuids "${_first}-${_last}" \
        --add-subgids "${_first}-${_last}" \
        "${_user}"

