# Run Prusa Slicer in a container
# Based on Brian C. Lane's post:
# https://www.brianlane.com/post/prusa-slicer/
# Based on Jessie Frazelle's post:
# https://blog.jessfraz.com/post/docker-containers-on-the-desktop/

FROM debian:unstable-slim
LABEL maintainer "Julie Koubova <julie@koubova.net>"

RUN apt-get update && apt-get install -y \
  bzip2 curl locales libegl1 libglu1-mesa prusa-slicer \
	&& rm -rf /var/lib/apt/lists/*

# Update the locale
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen en_US.utf8 \
    && /usr/sbin/update-locale LANG=en_US.UTF-8

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV HOME /home/user
ENV USER user

RUN groupadd -g 1000 user \
	&& useradd -u 1000 -g 1000 --create-home --home-dir $HOME user \
	&& chown -R user:user $HOME
RUN passwd -d root

WORKDIR $HOME
USER user

RUN curl -L --output prusa-slicer.tar.bz2 \
    https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.6.0-beta2/PrusaSlicer-2.6.0-beta2+linux-x64-GTK3-202305170854.tar.bz2 \
    && tar xfvj prusa-slicer.tar.bz2 

