FROM debian:unstable-slim
LABEL name="prusa-slicer" tag="version_2.6.0-beta4"

RUN apt-get update && apt-get install -y   bzip2 curl locales libegl1 libglu1-mesa prusa-slicer 	&& rm -rf /var/lib/apt/lists/*

# Update the locale
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen     && locale-gen en_US.utf8     && /usr/sbin/update-locale LANG=en_US.UTF-8

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV HOME /home/user
ENV USER user

RUN groupadd -g 1000 user 	&& useradd -u 1000 -g 1000 --create-home --home-dir $HOME user 	&& chown -R user:user $HOME
RUN passwd -d root

WORKDIR $HOME
USER user

#
# Download, extract, and cleanup the Linux x64 GTK3 pre-release version
RUN curl -LO "https://github.com/prusa3d/PrusaSlicer/releases/download/version_2.6.0-beta4/PrusaSlicer-2.6.0-beta4%2Blinux-x64-GTK3-202306021346.tar.bz2" && \
    mkdir -p "$HOME/prusa-slicer-version_2.6.0-beta4" && \
    tar xf "PrusaSlicer-2.6.0-beta4%2Blinux-x64-GTK3-202306021346.tar.bz2" -C "$HOME/prusa-slicer-version_2.6.0-beta4" --strip-components=1 && \
    rm "PrusaSlicer-2.6.0-beta4%2Blinux-x64-GTK3-202306021346.tar.bz2"
