#!/bin/sh
CMD=""
if [ -z "$1" ]; then
    CMD=prusa-slicer
else
    CMD="$*"
fi

podman run --rm -it \
  --userns=keep-id \
  --volume "$HOME/Downloads:/home/user/Downloads" \
  --volume /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix$DISPLAY" \
  --device /dev/dri \
  prusa-slicer "$CMD"
# xhost -si:localuser:"$USER"

