#!/bin/sh
CMD=""
if [ -z "$1" ]; then
    CMD=prusa-slicer
else
    CMD="$*"
fi
# xhost +si:localuser:"$USER"
podman run --rm -it --userns=keep-id -v "$HOME/Downloads:/home/user/Downloads" \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e "DISPLAY=unix$DISPLAY" \
prusa-slicer "$CMD"
# xhost -si:localuser:"$USER"
# -v "$PWD/PrusaSlicer:/home/user/.config/PrusaSlicer" \
