#!/bin/sh
set -e
cd "$(dirname $0)"

# Constants
PODMAN_IMAGE_NAME="prusa-slicer"

# Check if curl is installed
if ! command -v curl >/dev/null 2>&1; then
    echo "curl is not installed. Please install curl and try again."
    exit 1
fi

# Check if jq is installed
if ! command -v jq >/dev/null 2>&1; then
    echo "jq is not installed. Please install jq and try again."
    exit 1
fi

# Check if podman is installed
if ! command -v podman >/dev/null 2>&1; then
    echo "podman is not installed. Please install podman and try again."
    exit 1
fi

# Fetch the latest pre-release information from the GitHub API
release_info=$(curl -s "https://api.github.com/repos/prusa3d/PrusaSlicer/releases?per_page=1")

# Extract the release tag for the latest pre-release version
tag_name=$(echo "$release_info" | jq -r '.[0].tag_name')

# Check if the Podman image with the tag exists
if podman inspect "$PODMAN_IMAGE_NAME:$tag_name" >/dev/null 2>&1; then
    echo "The '$PODMAN_IMAGE_NAME:$tag_name' image already exists in Podman."
else
    # Extract the download URL for the Linux x64 GTK3 pre-release version with tar.bz2 extension
    download_url=$(echo "$release_info" | jq -r '.[0].assets[] | select(.name | test(".*linux.*x64.*GTK3.*\\.tar\\.bz2$")) | .browser_download_url')

    # Create a Containerfile
    cat <<EOF > Containerfile
FROM debian:unstable-slim
LABEL name="$PODMAN_IMAGE_NAME" tag="$tag_name"

RUN apt-get update && apt-get install -y \
  bzip2 curl locales libegl1 libglu1-mesa prusa-slicer \
	&& rm -rf /var/lib/apt/lists/*

# Update the locale
RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen en_US.utf8 \
    && /usr/sbin/update-locale LANG=en_US.UTF-8

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV HOME /home/user
ENV USER user

RUN groupadd -g 1000 user \
	&& useradd -u 1000 -g 1000 --create-home --home-dir \$HOME user \
	&& chown -R user:user \$HOME
RUN passwd -d root

WORKDIR \$HOME
USER user

#
# Download, extract, and cleanup the Linux x64 GTK3 pre-release version
RUN curl -LO "$download_url" && \\
    mkdir -p "\$HOME/prusa-slicer-$tag_name" && \\
    tar xf "$(basename "$download_url")" -C "\$HOME/prusa-slicer-$tag_name" --strip-components=1 && \\
    rm "$(basename "$download_url")"
EOF

    # Build the Podman image using the Containerfile
    echo "Building the '$PODMAN_IMAGE_NAME:$tag_name' image using Podman..."
    podman build -t "$PODMAN_IMAGE_NAME:$tag_name" .
    echo "Podman image built successfully."
fi

CMD=""
if [ -z "$1" ]; then
    CMD="/home/user/prusa-slicer-${tag_name}/prusa-slicer"
else
    CMD="$*"
fi

exec podman run --rm -it \
  --userns=keep-id \
  --volume "${HOME}/Downloads:/home/user/Downloads" \
  --volume /tmp/.X11-unix:/tmp/.X11-unix \
  -e "DISPLAY=unix${DISPLAY}" \
  --device /dev/dri \
  "${PODMAN_IMAGE_NAME}:${tag_name}" "$CMD"

